/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
    NavigationGuard,
        ParamValue,
        RouteLocationAsPathTypedList,
        RouteLocationAsRelativeTypedList,
        RouteLocationAsString,
        RouteLocationNormalizedLoadedTypedList,
        RouteLocationNormalizedTypedList,
        RouteLocationResolvedTypedList,
        // type safe route locations
        RouteLocationTypedList,
        // helper types
        // route definitions
        RouteRecordInfo,
        RouterLinkPropsTyped,
        RouterLinkTyped,
        UseLinkFnTyped,

        // data fetching
        _DataLoader,
        _DefineLoaderOptions,
        // vue-router extensions
        _RouterTyped
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
    export interface RouteNamedMap {
        '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
        'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
        'apps-calendar': RouteRecordInfo<'apps-calendar', '/apps/calendar', Record<never, never>, Record<never, never>>,
        'apps-chat': RouteRecordInfo<'apps-chat', '/apps/chat', Record<never, never>, Record<never, never>>,
        'apps-company-list': RouteRecordInfo<'apps-company-list', '/apps/company/list', Record<never, never>, Record<never, never>>,
        'apps-company-view-id': RouteRecordInfo<'apps-company-view-id', '/apps/company/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
        'apps-email': RouteRecordInfo<'apps-email', '/apps/email', Record<never, never>, Record<never, never>>,
        'apps-vacations-list': RouteRecordInfo<'apps-vacations-list', '/apps/vacations/list', Record<never, never>, Record<never, never>>,
        'apps-roles': RouteRecordInfo<'apps-roles', '/apps/roles', Record<never, never>, Record<never, never>>,
        'apps-signing-list': RouteRecordInfo<'apps-signing-list', '/apps/signing/list', Record<never, never>, Record<never, never>>,
        'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
        'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
        
        'apps-clients-list': RouteRecordInfo<'apps-clients-list', '/apps/clients/list', Record<never, never>, Record<never, never>>,
        'apps-clients-view-id': RouteRecordInfo<'apps-clients-view-id', '/apps/clients/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
        
        'apps-services-list': RouteRecordInfo<'apps-services-list', '/apps/services/list', Record<never, never>, Record<never, never>>,
        'apps-services-view-id': RouteRecordInfo<'apps-services-view-id', '/apps/services/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
        
        'apps-settings-list': RouteRecordInfo<'apps-settings-list', '/apps/settings/list', Record<never, never>, Record<never, never>>,
        
        'apps-schedule-list': RouteRecordInfo<'apps-schedule-list', '/apps/schedule/list', Record<never, never>, Record<never, never>>,
        
        "apps-bills-add": RouteRecordInfo<
            "apps-bills-add",
            "/apps/bills/add",
            Record<never, never>,
            Record<never, never>
        >;
        "apps-bills-list": RouteRecordInfo<
            "apps-bills-list",
            "/apps/bills/list",
            Record<never, never>,
            Record<never, never>
        >;
        "apps-bills-view-id": RouteRecordInfo<
            "apps-bills-view-id",
            "/apps/bills/view/:id",
            { id: ParamValue<true> },
            { id: ParamValue<false> }
        >;
        "apps-bills-report": RouteRecordInfo<
            "apps-bills-report",
            "/apps/bills/report",
            Record<never, never>,
            Record<never, never>
        >;
        
        'apps-citas-list': RouteRecordInfo<'apps-citas-list', '/apps/citas/list', Record<never, never>, Record<never, never>>,

        'apps-email-filter': RouteRecordInfo<'apps-email-filter', '/apps/email/:filter', { filter: ParamValue<true> }, { filter: ParamValue<false> }>,
        'apps-email-label': RouteRecordInfo<'apps-email-label', '/apps/email/:label', { label: ParamValue<true> }, { label: ParamValue<false> }>,
        'charts-apex-chart': RouteRecordInfo<'charts-apex-chart', '/charts/apex-chart', Record<never, never>, Record<never, never>>,
        'charts-chartjs': RouteRecordInfo<'charts-chartjs', '/charts/chartjs', Record<never, never>, Record<never, never>>,

        'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
        'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,

        'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
        'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
        'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
        'pages-authentication-forgot-password-v1': RouteRecordInfo<'pages-authentication-forgot-password-v1', '/pages/authentication/forgot-password-v1', Record<never, never>, Record<never, never>>,
        'pages-authentication-forgot-password-v2': RouteRecordInfo<'pages-authentication-forgot-password-v2', '/pages/authentication/forgot-password-v2', Record<never, never>, Record<never, never>>,
        'pages-authentication-login-v1': RouteRecordInfo<'pages-authentication-login-v1', '/pages/authentication/login-v1', Record<never, never>, Record<never, never>>,
        'pages-authentication-login-v2': RouteRecordInfo<'pages-authentication-login-v2', '/pages/authentication/login-v2', Record<never, never>, Record<never, never>>,
        'pages-authentication-register-multi-steps': RouteRecordInfo<'pages-authentication-register-multi-steps', '/pages/authentication/register-multi-steps', Record<never, never>, Record<never, never>>,
        'pages-authentication-register-v1': RouteRecordInfo<'pages-authentication-register-v1', '/pages/authentication/register-v1', Record<never, never>, Record<never, never>>,
        'pages-authentication-register-v2': RouteRecordInfo<'pages-authentication-register-v2', '/pages/authentication/register-v2', Record<never, never>, Record<never, never>>,
        'pages-authentication-reset-password-v1': RouteRecordInfo<'pages-authentication-reset-password-v1', '/pages/authentication/reset-password-v1', Record<never, never>, Record<never, never>>,
        'pages-authentication-reset-password-v2': RouteRecordInfo<'pages-authentication-reset-password-v2', '/pages/authentication/reset-password-v2', Record<never, never>, Record<never, never>>,
        'pages-authentication-two-steps-v1': RouteRecordInfo<'pages-authentication-two-steps-v1', '/pages/authentication/two-steps-v1', Record<never, never>, Record<never, never>>,
        'pages-authentication-two-steps-v2': RouteRecordInfo<'pages-authentication-two-steps-v2', '/pages/authentication/two-steps-v2', Record<never, never>, Record<never, never>>,
        'pages-authentication-verify-email-v1': RouteRecordInfo<'pages-authentication-verify-email-v1', '/pages/authentication/verify-email-v1', Record<never, never>, Record<never, never>>,
        'pages-authentication-verify-email-v2': RouteRecordInfo<'pages-authentication-verify-email-v2', '/pages/authentication/verify-email-v2', Record<never, never>, Record<never, never>>,
        'pages-user-profile-tab': RouteRecordInfo<'pages-user-profile-tab', '/pages/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
        'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,

        'apps-typeincidence-list': RouteRecordInfo<'apps-typeincidence-list', '/apps/typeincidence/list', Record<never, never>, Record<never, never>>,
        'apps-incidence-list': RouteRecordInfo<'apps-incidence-list', '/apps/incidence/list', Record<never, never>, Record<never, never>>,

        'apps-employee-list': RouteRecordInfo<'apps-employee-list', '/apps/employee/list', Record<never, never>, Record<never, never>>,
        'apps-employee-view-id': RouteRecordInfo<'apps-employee-view-id', '/apps/employee/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,

    }
}

declare module 'vue-router/auto' {
    import type { RouteNamedMap } from 'vue-router/auto/routes'

    export type RouterTyped = _RouterTyped<RouteNamedMap>

    /**
     * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
     * Allows passing the name of the route to be passed as a generic.
     */
    export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

    /**
     * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
     * Allows passing the name of the route to be passed as a generic.
     */
    export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

    /**
     * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
     * Allows passing the name of the route to be passed as a generic.
     */
    export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

    /**
     * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
     */
    export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

    /**
     * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
     */
    export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
        | RouteLocationAsString<RouteNamedMap>
        | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
        | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

    /**
     * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
     */
    export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
    /**
     * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
     */
    export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

    export function useRouter(): RouterTyped
    export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

    export const useLink: UseLinkFnTyped<RouteNamedMap>

    export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
    export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

    export const RouterLink: RouterLinkTyped<RouteNamedMap>
    export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

    // Experimental Data Fetching

    export function defineLoader<
        P extends Promise<any>,
        Name extends keyof RouteNamedMap = keyof RouteNamedMap,
        isLazy extends boolean = false,
        >(
            name: Name,
            loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
            options?: _DefineLoaderOptions<isLazy>,
    ): _DataLoader<Awaited<P>, isLazy>
    export function defineLoader<
        P extends Promise<any>,
        isLazy extends boolean = false,
        >(
            loader: (route: RouteLocationNormalizedLoaded) => P,
            options?: _DefineLoaderOptions<isLazy>,
    ): _DataLoader<Awaited<P>, isLazy>

    export {
        _HasDataLoaderMeta as HasDataLoaderMeta, _definePage as definePage, _setupDataFetchingGuard as setupDataFetchingGuard,
        _stopDataFetchingScope as stopDataFetchingScope
    } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
    import type { RouteNamedMap } from 'vue-router/auto/routes'

    export interface TypesConfig {
        beforeRouteUpdate: NavigationGuard<RouteNamedMap>
        beforeRouteLeave: NavigationGuard<RouteNamedMap>

        $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
        $router: _RouterTyped<RouteNamedMap>

        RouterLink: RouterLinkTyped<RouteNamedMap>
    }
}
